### ISSUE TITLE
Not reconnecting after offline

### ISSUE THREAD

**Issue by kesla** [nolanlawson/local-npm#51] opened 2015-10-14 12:20 UTC
Hey!

Thanks for local-npm, love it!
However, I've had some problems that when I've went offline for a while I'm behind the main registry and it doesn't seem to reconnect to get up to speed again...
I've tried restarting the local-npm process without any success. This is, using the OS X launch daemon (https://gist.github.com/nolanlawson/83ba5862bd719925d9cd).

Any tips on what I should do to get this working?

**Comment by nolanlawson** [comment] 2015-10-17 16:30
Hm, that's weird, I have exactly the same setup on my machine and it's been working perfectly for the past few months. Even if I turn the wifi on and off, it still works...

Can you run `pm2 logs all` to see if there's anything interesting in the logs? Also try updating your global pm2/local-npm installation; there have been some changes in the past few weeks.

**Comment by kesla** [comment] 2015-10-20 08:26
I'm on the latest version of local-npm, and looking at `pm2 logs all` I can see now that it tried to replicate the skimdb, got a timeout and then I can't see logging showing that it reconnected. So it's stuck at ~72%.

**Comment by kesla** [comment] 2015-10-20 08:27
```
local-npm-0 (out): Replicating skimdb, last_seq is: 265449 (68.91%)
local-npm-0 (out): Replicating skimdb, last_seq is: 266380 (69.15%)
local-npm-0 (out): Replicating skimdb, last_seq is: 267322 (69.4%)
local-npm-0 (out): Replicating skimdb, last_seq is: 268230 (69.63%)
local-npm-0 (out): Replicating skimdb, last_seq is: 269144 (69.87%)
local-npm-0 (out): Replicating skimdb, last_seq is: 269996 (70.09%)
local-npm-0 (out): Replicating skimdb, last_seq is: 270920 (70.33%)
local-npm-0 (out): Replicating skimdb, last_seq is: 271723 (70.54%)
local-npm-0 (out): Replicating skimdb, last_seq is: 272492 (70.74%)
local-npm-0 (out): Replicating skimdb, last_seq is: 273437 (70.98%)
local-npm-0 (out): Replicating skimdb, last_seq is: 274381 (71.23%)
local-npm-0 (out): Replicating skimdb, last_seq is: 275357 (71.48%)
local-npm-0 (out): Replicating skimdb, last_seq is: 276085 (71.67%)
local-npm-0 (out): Replicating skimdb, last_seq is: 277020 (71.91%)
local-npm-0 (out): Error: ETIMEDOUT
local-npm-0 (out): Error during replication with https://skimdb.npmjs.com/registry, retrying after 1000 ms...
local-npm-0 (out): GET / 200 93.782 ms - 151
local-npm-0 (out): GET / 200 13.988 ms - 151
local-npm-0 (out): GET / 304 23.635 ms - -
local-npm-0 (out): GET / 304 15.044 ms - -
```

**Comment by kesla** [comment] 2015-10-20 08:27
Or am I reading the logs in a bad way? :)

**Comment by nolanlawson** [comment] 2015-10-23 12:21
OK, I can confirm I see it in my own logs. Looks like what probably needs to be done is upgrade to PouchDB 5 and use the built-in retry replication.

**Comment by nolanlawson** [comment] 2015-10-23 12:31
I don't have time to look into this right now, but I started some work: https://github.com/nolanlawson/local-npm/tree/update-pouchdb-5

**Comment by kesla** [comment] 2015-10-23 12:39
@nolanlawson amazing, let me know if there's anything I can do to help.

**Comment by nolanlawson** [comment] 2015-10-24 03:07
OK it turned out to be a subtle bug in the pouchdb-security plugin, should be fixed with the latest release.

**Closed by nolanlawson** 2015-10-24 03:07 UTC

**Comment by kesla** [comment] 2015-10-24 13:43
@nolanlawson Thank you so much! It's working now it seem! :)
