### ISSUE TITLE
Could not resolve package

### ISSUE THREAD

**Issue by montogeek** [nolanlawson/local-npm#117] opened 2016-04-08 19:50 UTC
Hi!

This tool has been working extremely well for me for more than a month now, thanks for create it :)

Recently it have presenting an error regarding a package: `for-in`

Error:
```bash
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/montogeek/.nvm/versions/v5.3.0/bin/node" "/Users/montogeek/.nvm/versions/v5.3.0/bin/npm" "i"
npm ERR! node v5.3.0
npm ERR! npm  v3.6.0

npm ERR! No compatible version found: for-in@^0.1.5
npm ERR! Valid install targets:
npm ERR! 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/montogeek/project/npm-debug.log
```

local-npm is 100% synced with the registry

**Comment by DutchmanSA** [comment] 2016-04-19 10:21
I have exactly the same issue with babel-traverse@6.7.6. The version on my local-npm is 6.7.4, but the latest on npmjs.org is 6.7.6 and an install dependency requires 6.7.6. Is there a way to force an update of a package version with local-npm?

**Comment by nolanlawson** [comment] 2016-04-20 12:17
Thanks for reporting! Looks like a duplicate of https://github.com/nolanlawson/local-npm/issues/79

**Closed by nolanlawson** 2016-04-20 12:17 UTC
