### ISSUE TITLE
SHA missmatches

### ISSUE THREAD

**Issue by IngwiePhoenix** [nolanlawson/local-npm#84] opened 2016-01-14 06:45 UTC
```
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12

npm ERR! shasum check failed for /var/folders/kz/l3s2fpd51ln9_p9ymvqbyshm0000gr/T/npm-85850-aee4b87e/127.0.0.1_5080/tarballs/karma-phantomjs-launcher/0.2.3.tgz
npm ERR! Expected: 77f68243fad7852c5b321bcf9d691f1223cc0809
npm ERR! Actual:   971e32af3eeb22d6165a10d8bc214d981701024f
npm ERR! From:     http://127.0.0.1:5080/tarballs/karma-phantomjs-launcher/0.2.3.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Ingwie/Work/BIRD3/npm-debug.log
```

How do I fix that? :/ It keeps happening, and clearing my cache did not do a thing.

**Comment by IngwiePhoenix** [comment] 2016-01-14 08:15
Actually, I looked at the file another time that i got the failure, since no installs at all work. So...

```
Ingwie@Ingwies-Macbook-Pro.local ~/.local-npm $ file /var/folders/kz/l3s2fpd51ln9_p9ymvqbyshm0000gr/T/npm-43056-89bbb31c/127.0.0.1_5080/tarballs/npmrc/1.1.1.tgz
/var/folders/kz/l3s2fpd51ln9_p9ymvqbyshm0000gr/T/npm-43056-89bbb31c/127.0.0.1_5080/tarballs/npmrc/1.1.1.tgz: ASCII text, with no line terminators
Ingwie@Ingwies-Macbook-Pro.local ~/.local-npm $ cat /var/folders/kz/l3s2fpd51ln9_p9ymvqbyshm0000gr/T/npm-43056-89bbb31c/127.0.0.1_5080/tarballs/npmrc/1.1.1.tgz
"getaddrinfo ENOTFOUND"
```

Interesting! My launch script:

```sh
#!/bin/bash
pm2 start `which local-npm` -- \
	--remote http://registry.npmjs.org/
```

(I use HTTP instead of HTTPS, since, for whatever reason, HTTPS is slower and at some point drops conections.)

Any idea whats up?

**Comment by nolanlawson** [comment] 2016-01-15 02:32
Maybe your tarballs are actually being maliciously modified by your ISP on the way in? Since you are using HTTP?

Otherwise, unfortunately I would need steps to reproduce to understand what's happening. E.g. `npm install some-weird-package` that reproduces the error.

**Comment by IngwiePhoenix** [comment] 2016-01-15 02:37
Also, mind the `ENOTFOUND` that is actually written in place of the tarbal, as demonstrated above.

**Comment by nolanlawson** [comment] 2016-01-15 02:47
Unfortunately I cannot reproduce using the steps you provided (on OS X, using local-npm 1.5.3, default registry over https instead of http). `npm install` successfully completed with no error status. Maybe try a `npm cache clear` and `rm -fr node_modules` and then try `npm install` again?

**Comment by IngwiePhoenix** [comment] 2016-01-15 03:02
No luck.

```
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12

npm ERR! shasum check failed for /var/folders/kz/l3s2fpd51ln9_p9ymvqbyshm0000gr/T/npm-90279-dfe83e33/127.0.0.1_5080/tarballs/mkdirp/0.5.1.tgz
npm ERR! Expected: 30057438eac6cf7f8c4767f38648d6697d75c903
npm ERR! Actual:   971e32af3eeb22d6165a10d8bc214d981701024f
npm ERR! From:     http://127.0.0.1:5080/tarballs/mkdirp/0.5.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Ingwie/Work/BIRD3/npm-debug.log
Ingwie@Ingwies-Macbook-Pro.local ~/W/BIRD3 $ file /var/folders/kz/l3s2fpd51ln9_p9ymvqbyshm0000gr/T/npm-90279-dfe83e33/127.0.0.1_5080/tarballs/mkdirp/0.5.1.tgz
/var/folders/kz/l3s2fpd51ln9_p9ymvqbyshm0000gr/T/npm-90279-dfe83e33/127.0.0.1_5080/tarballs/mkdirp/0.5.1.tgz: ASCII text, with no line terminators
Ingwie@Ingwies-Macbook-Pro.local ~/W/BIRD3 $ cat /var/folders/kz/l3s2fpd51ln9_p9ymvqbyshm0000gr/T/npm-90279-dfe83e33/127.0.0.1_5080/tarballs/mkdirp/0.5.1.tgz
"getaddrinfo ENOTFOUND"
```

I am so lost. I will try to use the default parameters without anything else and operate `local-npm` just on its defaults and see if that does something. Because when I visit the local path and see the "mini npm", I can also see the packages. Well, going to try that now.

**Comment by IngwiePhoenix** [comment] 2016-01-15 03:05
Nope, same problem. Even on defaults.

**Comment by IngwiePhoenix** [comment] 2016-01-15 03:07
Just found this in the output of the srver itself:

```
not cached redis at version 2.4.2, downloading...
hashes don't match, not returning
```

I used `tail -f`, so there might be more.

**Comment by IngwiePhoenix** [comment] 2016-01-15 03:10
Just re-tried, but instead kept tailing. Turns out that the message pops up for an alarming amount. It seems that `local-npm` is unable to download stuff itself. Or, at least, it gets wrong stuff.

This might be related to the error that I see printed into the wanna-be tarball:

```
"getaddrinfo ENOTFOUND"
```

How can I debug that?

**Comment by nolanlawson** [comment] 2016-01-15 05:39
Ohhh, I know what's happening. Sorry. This is due to the http/https stuff. I think I know what the fix is.

**Comment by nolanlawson** [comment] 2016-01-15 05:43
Check out https://github.com/nolanlawson/local-npm/pull/87

**Comment by nolanlawson** [comment] 2016-01-15 05:50
Should be fixed in 1.5.4. Sorry for the troubles!

**Closed by nolanlawson** 2016-01-15 05:50 UTC
Labels: bug

**Comment by IngwiePhoenix** [comment] 2016-01-15 06:10
Yes, 1.5.4 fixed it. Im so curios i’m going to check out the commit that did the magic :).

Thanks for fixing!

**Comment by nolanlawson** [comment] 2016-01-15 13:08
No prob! It was a dumb mistake on my part. :P

**Comment by MichaelJCole** [comment] 2017-09-17 18:57
Hey, ran into this.  Is there a workaround?  Seems like deleting local-npm's database and resyncing is the best option, but ... well ...  I'm limited in my bandwidth at the moment.

**Comment by gabrielcsapo** [comment] 2017-09-18 00:10
@MichaelJCole in order to delete from pouch, you have to set an admin user account up and then log in via that to delete

**Comment by MichaelJCole** [comment] 2017-09-18 00:37
@gabrielcsapo hey, I think I ran into this because I did an `npm install` before clicking the "accept free wifi" button at a bigbox wifi spot.  Anyways, is there an easy way to clear the cashed tgz for a package?  I think this bug should be reopened to have local-npm drop the incorrectly cached file automatically.

**Comment by gabrielcsapo** [comment] 2017-09-18 00:45
@michaeljcole if you could open a new issue we can track the bug there. We would need to be able to reproduce that problem and determine if we can use headers the client sends to the server to resolve cache problems

**Comment by gabrielcsapo** [comment] 2017-09-18 19:36
@MichaelJCole this also a flaw in the caching as it does inspect the headers to validate source
