### ISSUE TITLE
npm install node-sass fails with "No compatible version found"

### ISSUE THREAD

**Issue by gr2m** [nolanlawson/local-npm#103] opened 2016-02-17 17:26 UTC
I get the same error for both, `npm install node-sass` and `npm install node-sass@latest`

```
$ npm i node-sass@latest
npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/gregor/.nvm/versions/node/v4.2.2/bin/node" "/Users/gregor/.nvm/versions/node/v4.2.2/bin/npm" "i" "node-sass@latest"
npm ERR! node v4.2.2
npm ERR! npm  v3.5.2

npm ERR! No compatible version found: node-sass@latest
npm ERR! Valid install targets:
npm ERR! 3.5.0-beta.1, 3.4.2, 3.4.1, 3.4.0, 3.4.0-beta1, 3.4.0-beta.2, 3.3.3, 3.3.2, 3.3.1, 3.3.0, 3.2.0, 3.1.2, 3.1.1, 3.1.0, 3.0.0, 3.0.0-beta.7, 3.0.0-beta.5, 3.0.0-beta.4, 3.0.0-beta.3, 3.0.0-beta.2, 3.0.0-alpha.0, 2.1.1, 2.1.0, 2.0.1, 2.0.0, 2.0.0-beta, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.3, 1.0.2, 1.0.2-alpha, 1.0.1, 1.0.0, 0.9.6, 0.9.5, 0.9.5-rc1, 0.9.4, 0.9.4-rc1, 0.9.3, 0.9.2, 0.9.1, 0.9.0, 0.8.6, 0.8.5, 0.8.4, 0.8.3, 0.8.2, 0.8.1, 0.8.0, 0.7.0, 0.7.0-alpha, 0.6.7, 0.6.6, 0.6.5, 0.6.4, 0.6.3, 0.6.2, 0.6.1, 0.6.0, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.5.0, 0.4.4, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.0, 0.2.6, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/npm-debug.log
```

Outputh with `loglevel=silly`: https://gist.github.com/f11dfb3b2c3e2b04d480

The issue does not occur when using the standard registry (`npm set registry https://registry.npmjs.org`).

This works: `npm install node-sass@3.4.2`

I've updated local-npm to the latest version

```
$ local-npm --version
1.5.7
````

All packages are synced (`Replicating skimdb, last_seq is: 768417 (100%)`)

**Comment by nolanlawson** [comment] 2016-02-17 18:50
Looks like the bug is that node-sass somehow has:

    'dist-tags': { latest: 'v3.4.2', beta: 'v3.5.0-beta.1' },

`local-npm` isn't smart enough to remove the `v` apparently.

**Comment by marthinus-engelbrecht** [comment] 2016-04-15 07:21
I'm getting the same issue for `cross-spawn-async` but the dist-tags doesn't have a `v` in it `"dist-tags":{"latest":"2.2.2"}`. It looks like local-npm is not pulling down the latest package. See below: 

<img width="806" alt="screen shot 2016-04-15 at 9 19 25 am" src="https://cloud.githubusercontent.com/assets/8449253/14554166/50863cb2-02eb-11e6-917a-20ce8fa2fb54.png">

**Comment by DutchmanSA** [comment] 2016-04-19 10:30
I have exactly the same issue with babel-traverse@6.7.6. The version on my local-npm is 6.7.4, but the latest on npmjs.org is 6.7.6 and an install dependency requires 6.7.6.

**Comment by gr2m** [comment] 2016-04-19 14:41
@marthinus-engelbrecht @DutchmanSA maybe a temporary sync hiccup? I got both, `cross-spawn-async@2.2.2` and `babel-traverse@6.7.6` in my local-npm

**Comment by marthinus-engelbrecht** [comment] 2016-04-19 14:56
@gr2m Yeah, getting the right version now.

**Comment by DutchmanSA** [comment] 2016-04-19 15:35
I'll have another look and also check local-npm running on my home mac. Maybe it is because my local-npm doesnt run permanently on a server host? So the question then is, is there no way to force a version update, similar to when you start local-npm for the first time and run npm install, it will go download the packages in question while syncing up. Why does it not do the same for when a version is missing locally, but yet available in the public registry?

**Comment by gr2m** [comment] 2016-04-19 15:46
> Why does it not do the same for when a version is missing locally, but yet available in the public registry

You mean "why _doesn’t_"? Sounds like a good addition to me, CouchDB’s maybe send a PR?

**Comment by nolanlawson** [comment] 2016-04-20 12:24
Closing as duplicate of #79. This may be a bug in PouchDB actually. I've run into the same thing, looking to update PouchDB to fix.

**Closed by nolanlawson** 2016-04-20 12:24 UTC
